{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\"]\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc', '+@aggarwal_kartik.\\nCongrats! Wish you many more success.']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc', '+@aggarwal_kartik.\\nCongrats! Wish you many more success.', 'RT @aggarwal_kartik: Our work (@midasIIITD ) accepted at SemEval 2019 at @NAACLHLT : \"MIDAS at SemEval-2019 Task 9: Suggestion Mining from…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc', '+@aggarwal_kartik.\\nCongrats! Wish you many more success.', 'RT @aggarwal_kartik: Our work (@midasIIITD ) accepted at SemEval 2019 at @NAACLHLT : \"MIDAS at SemEval-2019 Task 9: Suggestion Mining from…', 'Congratulations! @midasIIITD team, @isarth23 @LaibaMehnaz @Simcyy @debanjanbhucs @RatnRajiv @the_dhumketu for getti… https://t.co/z8pT3ojhoP']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc', '+@aggarwal_kartik.\\nCongrats! Wish you many more success.', 'RT @aggarwal_kartik: Our work (@midasIIITD ) accepted at SemEval 2019 at @NAACLHLT : \"MIDAS at SemEval-2019 Task 9: Suggestion Mining from…', 'Congratulations! @midasIIITD team, @isarth23 @LaibaMehnaz @Simcyy @debanjanbhucs @RatnRajiv @the_dhumketu for getti… https://t.co/z8pT3ojhoP', '@EEMLcommunity @radamihalcea too many deadlines coming, @ACMMM19 @IEEEBigMM19 @EEMLcommunity']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc', '+@aggarwal_kartik.\\nCongrats! Wish you many more success.', 'RT @aggarwal_kartik: Our work (@midasIIITD ) accepted at SemEval 2019 at @NAACLHLT : \"MIDAS at SemEval-2019 Task 9: Suggestion Mining from…', 'Congratulations! @midasIIITD team, @isarth23 @LaibaMehnaz @Simcyy @debanjanbhucs @RatnRajiv @the_dhumketu for getti… https://t.co/z8pT3ojhoP', '@EEMLcommunity @radamihalcea too many deadlines coming, @ACMMM19 @IEEEBigMM19 @EEMLcommunity', 'RT @stanfordnlp: CS224N Natural Language Processing with Deep Learning 2019 @Stanford course videos by @chrmanning, @abigail_e_see &amp; guests…']\n",
      "['We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw', 'RT @rfpvjr: Our NAACL paper on polarization in language on Twitter surrounding mass shootings is up on arXiv! https://t.co/g7wiegXxDg\\nThis…', 'RT @kdnuggets: Effective Transfer Learning For NLP https://t.co/Z1m0AzlfVv https://t.co/ccX4Uhxjn8', 'RT @stanfordnlp: What’s new in @Stanford CS224N Natural Language Processing with Deep Learning for 2019? Question answering—1D CNNs—subword…', \"RT @DeepMindAI: Today we're releasing a large-scale extendable dataset of mathematical questions, for training (and evaluating the abilitie…\", 'RT @ylecun: Congratulations Jitendra Malik !\\n\\nAwards are raining on FAIRies these days... https://t.co/1WNcSeQLZe', 'RT @IIITDelhi: Another chance to take admission in the Ph.D. program in IIIT Delhi. \\nAdmissions open for Ph.D. program mathematics \\n\\nLog on…', 'Dear @midasIIITD internship candidates who have submitted their solutions to the task, we have sent you an email re… https://t.co/4lCcAmwBKc', 'Looking forward to your paper submission to @IEEEBigMM19. \\n\\nImportant Dates:\\nRegular Paper: 11:59pm PST, May 10, 20… https://t.co/ODYKLC8z0s', 'RT @ngrams: Reproducibility in multimedia research in @sigmm records https://t.co/hOyMxtmy7A Plus reminder to past-year authors: Today 1 Ap…', 'Online application for https://t.co/DJFDrQsHZP. Admission 2019 at @IIITDelhi has been open\\n\\nLog on to know more and… https://t.co/iqmGyRn1R0', 'RT @ACMMM19: A final reminder of the Reproducibility Track: Authors of 2017 and 2018 papers are invited to submit a short reproducibility p…', 'RT @isarth23: Thanks for the support and help @debanjanbhucs @RatnRajiv and @midasIIITD. It was a great learning experience! Glad to be par…', 'Since SemEval-2019 will be held June 6-7, 2019 in Minneapolis, USA, collocated with NAACL-HLT 2019, it will great s… https://t.co/Jrl1uSesPc', '+@aggarwal_kartik.\\nCongrats! Wish you many more success.', 'RT @aggarwal_kartik: Our work (@midasIIITD ) accepted at SemEval 2019 at @NAACLHLT : \"MIDAS at SemEval-2019 Task 9: Suggestion Mining from…', 'Congratulations! @midasIIITD team, @isarth23 @LaibaMehnaz @Simcyy @debanjanbhucs @RatnRajiv @the_dhumketu for getti… https://t.co/z8pT3ojhoP', '@EEMLcommunity @radamihalcea too many deadlines coming, @ACMMM19 @IEEEBigMM19 @EEMLcommunity', 'RT @stanfordnlp: CS224N Natural Language Processing with Deep Learning 2019 @Stanford course videos by @chrmanning, @abigail_e_see &amp; guests…', 'RT @ylecun: Learn PyTorch by running on Google GPUs for free. https://t.co/pt038TMnWR']\n"
     ]
    }
   ],
   "source": [
    "import tweepy\n",
    "import json\n",
    "consumer_key = \"qZxyo16WKljqfEyX6N0141IqW\" \n",
    "consumer_secret = \"JVKWmVTT1bxHkNadfmEb1O1j9mQtlCwgr8wKOw0d5LnJxKsr2A\"\n",
    "access_key = \"937004786481635328-kNxGkjB00W7uL1Srr7SqJL3FcR06wFn\"\n",
    "access_secret = \"CozseEdSi9PQVhGdHCtusMN1MfmDIbFOep5ELqiNFNUPf\"\n",
    "\n",
    "\n",
    "def getTweets(username):\n",
    "    auth=tweepy.OAuthHandler(consumer_key,consumer_secret)\n",
    "    auth.set_access_token(access_key,access_secret)\n",
    "    api=tweepy.API(auth)\n",
    "    \n",
    "    tweets=api.user_timeline(screen_name=username,no_of_tweets=3200)\n",
    "    tmp=[]  \n",
    "    tweets_for_csv = [tweet.text for tweet in tweets] # CSV file created  \n",
    "    for j in tweets_for_csv: \n",
    "  \n",
    "            # Appending tweets to the empty array tmp \n",
    "        tmp.append(j)  \n",
    "  \n",
    "        # Printing the tweets \n",
    "        print(tmp) \n",
    "    \n",
    "    \n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    getTweets(\"@midasIIITD\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "with jsonlines.open('output.jsonl', mode='w') as writer:\n",
    "    writer.write(...)\n",
    "    txt=list()\n",
    "    \n",
    "    txt=[tweet.text for tweet in tweets]\n",
    "    for _ in txt :\n",
    "        #print(_+'\\n')\n",
    "        pass"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
